import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { SignIn } from "@clerk/nextjs";
import { SignInButton } from "@clerk/nextjs";
import { SignOutButton,useUser } from "@clerk/nextjs";

const Home: NextPage = () => {
  const user = useUser();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

      <div>
        <h1>Hello</h1>

        <div>
        {!user.isSignedIn && <SignInButton/>}

       {!!user.isSignedIn && <SignOutButton/>}
        </div>


     
    </div>
    <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
    </main>
    </>
  );
};

export default Home;
